colorscheme hybrid
"set background=dark
syntax on
set transparency=10
set guifont=Ricty_Discord:h14
set imdisable
"English Menu
source $VIMRUNTIME/delmenu.vim
set langmenu=none
source $VIMRUNTIME/menu.vim
