::Make windows sym-links.
::Windows native
mklink    "%USERPROFILE%\_gvimrc"             "%USERPROFILE%\dotfiles\.gvimrc"
mklink /D "%USERPROFILE%\vimfiles"            "%USERPROFILE%\dotfiles\.vim"
mklink    "%USERPROFILE%\_vimrc"              "%USERPROFILE%\dotfiles\.vimrc"
mklink /D "%USERPROFILE%\vimperator"          "%USERPROFILE%\dotfiles\.vimperator"
mklink    "%USERPROFILE%\.vimperatorrc"       "%USERPROFILE%\dotfiles\.vimperatorrc"
mklink    "%USERPROFILE%\.bash_profile"       "%USERPROFILE%\dotfiles\.bash_profile"
mklink    "%USERPROFILE%\.bashrc"             "%USERPROFILE%\dotfiles\.bashrc"
mklink    "%USERPROFILE%\.inputrc"            "%USERPROFILE%\dotfiles\.inputrc"
mklink    "%USERPROFILE%\.minttyrc"           "%USERPROFILE%\dotfiles\.minttyrc"
mklink /D "%USERPROFILE%\.zsh"                "%USERPROFILE%\dotfiles\.zsh"
mklink    "%USERPROFILE%\.zshenv"             "%USERPROFILE%\dotfiles\.zshenv"
mklink    "%USERPROFILE%\.tmux.conf"          "%USERPROFILE%\dotfiles\.tmux.conf"
=======
mklink    "%USERPROFILE%\_gvimrc"       "%USERPROFILE%\dotfiles\.gvimrc"
mklink /D "%USERPROFILE%\vimfiles"      "%USERPROFILE%\dotfiles\.vim"
mklink    "%USERPROFILE%\_vimrc"        "%USERPROFILE%\dotfiles\.vimrc"
mklink    "%USERPROFILE%\.bash_profile" "%USERPROFILE%\dotfiles\.bash_profile"
mklink    "%USERPROFILE%\.bashrc"       "%USERPROFILE%\dotfiles\.bashrc"
mklink    "%USERPROFILE%\.inputrc"      "%USERPROFILE%\dotfiles\.inputrc"
mklink /D "%USERPROFILE%\.zsh"          "%USERPROFILE%\dotfiles\.zsh"
mklink    "%USERPROFILE%\.zshenv"       "%USERPROFILE%\dotfiles\.zshenv"
