::WIndows native
::mklink /D "%HOME%/vimperator" "%HOME%/dotfiles/.vimperator"
::mklink /D "%HOME%/vimfiles" "%HOME%/dotfiles/.vim"
::mklink "%HOME%/.vimperatorrc" "%HOME%/dotfiles/.vimperatorrc"
::mklink "%HOME%/_vimrc" "%HOME%/dotfiles/.vimrc"
::mklink "%HOME%/_gvimrc" "%HOME%/dotfiles/.gvimrc"
::mklink "%HOME%/.inputrc" "%HOME%/dotfiles/.inputrc"
::Cygwin or msys2
mklink    "C:\msys64\home\%USERNAME%\.bash_profile" "C:\msys64\home\%USERNAME%\dotfiles\.bash_profile"
mklink    "C:\msys64\home\%USERNAME%\.bashrc"       "C:\msys64\home\%USERNAME%\dotfiles\.bashrc"
mklink    "C:\msys64\home\%USERNAME%\.inputrc"      "C:\msys64\home\%USERNAME%\dotfiles\.inputrc"
mklink    "C:\msys64\home\%USERNAME%\.minttyrc"     "C:\msys64\home\%USERNAME%\dotfiles\.minttyrc"
mklink    "C:\msys64\home\%USERNAME%\.gvimrc"       "C:\msys64\home\%USERNAME%\dotfiles\.gvimrc"
mklink /D "C:\msys64\home\%USERNAME%\.vim"          "C:\msys64\home\%USERNAME%\dotfiles\.vim"
mklink    "C:\msys64\home\%USERNAME%\.vimrc"        "C:\msys64\home\%USERNAME%\dotfiles\.vimrc"
mklink /D "C:\msys64\home\%USERNAME%\.zsh"          "C:\msys64\home\%USERNAME%\dotfiles\.zsh"
mklink    "C:\msys64\home\%USERNAME%\.zshenv"       "C:\msys64\home\%USERNAME%\dotfiles\.zshenv"
mklink    "C:\msys64\home\%USERNAME%\.tmux.conf"    "C:\msys64\home\%USERNAME%\dotfiles\.tmux.conf"
::Vimperator files is in the
mklink /D "C:\Users\%USERNAME%\vimperator"          "C:\msys64\home\%USERNAME%\dotfiles\.vimperator"
mklink    "C:\Users\%USERNAME%\.vimperatorrc"       "C:\msys64\home\%USERNAME%\dotfiles\.vimperatorrc"
